def operacao_risco():
        try:
                x = int("dez")
        except Exception as e:
                print(f"Ocorreu um erro inesperado: {e}")

operacao_risco()